### PR TITLE
Update golang1.19

### PR DESCRIPTION
**Pull request by vrindle**

### CODE REVIEW

**Comment by wizhaoredhat** [comment]
@vrindle Why don't we just do a sync from U/S to D/S?

**Comment by vrindle** [comment]
> @vrindle Why don't we just do a sync from U/S to D/S?

The reason I don't really know the ramifications of syncing the entire upstream with the downstream repo. I did this so I may fix the CVE and update the golang version so it more new. I am hesitant to completely sync with upstream because at this point the 2 branches have diverged and we don't know if we want everything from upstream to be in downstream.

**Comment by wizhaoredhat** [comment]
Please evaluate how many commits have we diverged? We will need to sync with U/S.

**Comment by bn222** [comment]
We shouldn't delete Dockerfile.rhel7. I know the file name is a bit unfortunate, but we shouldn't delete it either way.

Next, we should have 2 separate commits, one to bump the version, and one where you run vendoring golang commands. I'd like to keep the history as clean as possible.

**Pull request closed without merging**
